### ISSUE TITLE
Check that flowMax()'s arguments are functions

### ISSUE THREAD

**Issue by helixbass** [helixbass/ad-hok#12]
Getting an obscure error message `TypeError: Cannot read property '__ad-hok-flowMax-getArguments' of undefined` that looks like it'd be due to passing something other than a function as an argument to `flowMax()`

Should just check if all arguments are functions and throw a nice error if not - I believe `flow()` does this?

**Comment by peterstuart** [comment]
Related, I wondered if it might make sense to have "magic" helpers return something other than functions, so that they will make `flow` fail explicitly (instead of silently failing) when you should be using `flowMax`. Maybe something like:

```js
{
  type: 'magic',
  helper: // the actual helper function goes here
}
```

**Comment by helixbass** [comment]
That's a great idea - I don't see any reason why it wouldn't work (since `flowMax()` always has to sniff the magic helpers anyway, and I don't think there's any use case where we want anything other than `flowMax()` calling magic helpers)

So basically rather than let `flowMax()` sniff magic helpers via a property set on a function, just return an object and let `flowMax()` sniff that

Using a consistent eg `type: 'magic'` could work. But I wonder, if we'll still need to be able to distinguish them from each other via a "marker property" (eg currently `__ad-hok-addPropTypes`), then it would probably suffice to just still set the same marker property and detect it that way?

But there's also no more need for the "obscurity" of the marker property since we can definitively tell the difference by type-checking if it's not a function (and is a magic helper rather than a stray non-function)

So could be eg
```
{
  '__ad-hok-type': 'addPropTypes', // might as well use an obscure property name here to confidently distinguish magic helpers from "accidentally used a non-function"
  helper: ...
```

This seems to have these benefits beyond resolving the original issue (of nicer error messages when you pass a non-function to a `flowMax()`):
- Like you said, not having `flow()` that should be `flowMax()` fail silently
- At that point, choosing whether to "default to using `flowMax()`" could be more a matter of taste since if you have a `flow()` that needs to become a `flowMax()` it won't fail silently (so as long as you know you're exercising that code path eg in tests, you'd always catch it and should be pretty easy to tell what's going on)
- The ESLint rule `needs-flowmax` could still occasionally come in handy for immediate feedback, but it can't catch any cases where the magic helper is used via a "secondary" helper (and is out-of-date at the moment as far as its list of magic helpers). Whereas this would provide a reliable runtime way of indicating it (assuming that indeed `flow()` throws a nice error message when it's given a non-function and that it's pretty easy to know based on that error message "ok that usually means I need to use `flowMax()`")

**Comment by helixbass** [comment]
Actually starting to look at implementation, there's one case we can't cover using this technique - nested `flowMax()`'s. Since they have to look like normal functions to callers but also be able to be sniffed by `flowMax()`

Basically I don't see a way that you could detect (at runtime or at build time in ESLint) that a `flow()` contains a nested `flowMax()` (unless it's defined inline, which would be weird)

That's unfortunate since that's the primary use case for what `needs-flowmax` can't catch and probably for forgetting to use `flowMax()` since when you define a multi-step "secondary helper" which contains magic it's always implemented as a `flowMax()`

So that probably implies that using `flowMax()` by default is (still) good practice

But it seems like it'd still be worth using the technique for other magic helpers since you'd still get the benefit of not failing silently if you use them "directly" (either inlined in a `flow()` (which `needs-flowmax` can catch, but not everyone will use the ESLint plugin) or via a secondary helper that's *just* a single magic helper rather than a secondary `flowMax()`)

**Comment by peterstuart** [comment]
I think that it conceptually would make sense for `flowMax` to return an object rather than a function (the same as the other magic helpers), and then wherever it's finally going to be used, you could call `toFunction()` on it to unwrap it. That would ugly up usage of it a bit though, and I'd probably rename it to avoid comparisons with `flow`.

**Comment by helixbass** [comment]
Ya I don't think it's worth sacrificing the basic usability of it/calling-interface compatibility with `flow()` just to try and avoid accidental nesting of a `flowMax()` inside a `flow()`

If it could be implemented relatively cleanly on top of `flowMax()`, I'd be open to exposing a version (under whatever non-`flow`-based name) that behaved this way for people who found that preferable. But even that I'd want to think about before going ahead and doing it since from an API design perspective there's something to be said for there only being one way to use the magic helpers (via `flowMax()`)

**Comment by helixbass** [comment]
If your primary concern (as opposed to just liking the conceptual symmetry of `flowMax()` as an object) is that there would be times you'd forget to use `flowMax()` and have silent failures, I sketched out an idea for an ESLint rule (that off the top of my head seems relatively straightforward to implement) that should allow you to "err on the side of being cautious" wrt avoiding that situation: https://github.com/helixbass/eslint-plugin-ad-hok/issues/3

**Comment by peterstuart** [comment]
> as opposed to just liking the conceptual symmetry of flowMax() as an object

That was the main thing 😛. I think using `flowMax` by default will mostly solve my practical concerns. I do feel like this isn't quite the right abstraction around what `flowMax` is doing, but it works.

**Comment by helixbass** [comment]
For now just mimicking `flow()` and throwing a `TypeError` if an argument to `flowMax()` isn't a function

I've been finding the ESLint setup to work very smoothly in practice which makes me a little more hesitant to introduce additional complexity around having the magic helpers not return functions
