### ISSUE TITLE
Only use flowMax() in docs

### ISSUE THREAD

**Issue by helixbass** [helixbass/ad-hok#48]
Per discussion in #40, it's probably only adding confusion when learning ad-hok to explain `flow()` vs `flowMax()`

So should probably update the README to:

1. Only use `flowMax()` in examples
1. Not differentiate/mention the "magic"-ness of helpers
1. Possibly add a section toward the end of the README encapsulating all of the `flow()` vs `flowMax()`/"magic"-ness stuff (or link to eg an article or another wiki page that explains it, and why you might care)

And then I think it'll be worth considering how to update the `eslint-plugin-ad-hok` README so that there's not a disconnect between the two (eg "why are all these rules about `flow()` vs `flowMax()` when the ad-hok docs don't even mention `flow()`?") - I still want those rules to exist in `eslint-plugin-ad-hok`, since they're what enables a nice workflow if you want to use `flow()` when it suffices, but they probably require some additional explanation (eg linking to the same thing as # 3 above)

cc @peterstuart @mattpetrie @alexmay

**Comment by helixbass** [comment]
Erp cc @amay

**Comment by amay** [comment]
I agree with the idea of picking a sane default here and leaving the nuances and details to power users who want to understand the difference. It could likely suffice to point out that `flowMax` is being used to abstract away some of the details and it does work differently than lodash `flow`, but then link out to a separate article that dives into the details.
