### ISSUE TITLE
Docs: dependencies as callback

### ISSUE THREAD

**Issue by helixbass** [helixbass/ad-hok#52]
I think all of the helpers that accept a dependencies argument allow that dependencies argument to be either a list of prop names/paths or a callback of oldProps/newProps

But the docs currently just describe dependencies as an array

**Comment by peterstuart** [comment]
Maybe handle #33 at the same time?

**Comment by helixbass** [comment]
Oh ya I guess that's really a duplicate, I just renamed #33 since parts of it have already been done, but looks like "explain that prevProps is always non-null" is really a follow-on point to "update docs to reflect path/callback dependencies args"

So I'll rename it again and close this
