### ISSUE TITLE
Throw an error if an argument to flowMax is undefined (or not a function)

### ISSUE THREAD

**Issue by peterstuart** [helixbass/ad-hok#57]
The error message you get if you accidentally do this is not very clear.

**Comment by helixbass** [comment]
@peterstuart can you reproduce/give an example?

This should have been fixed awhile ago by https://github.com/helixbass/ad-hok/pull/26

**Comment by peterstuart** [comment]
```typescript
const x = flowMax(undefined as any);
```
throws this error:
```
Cannot read property '__ad-hok-flowMax-getArguments' of undefined
```
